oicq:
  platform: 3
  log_level: info

id: ${BOT_ID}
admins: 
  - ${ADMIN_ID}

giveme20:
  base_url: ${GIVEME20_URL}
  update_interval: ${GIVEME20_UPDATE_INTERVAL}
  groups_id:
    - ${GIVEME20_GROUP_ID}
