debug: true
oicq:
  platform: 4
  log_level: info

id: ${BOT_ID}
password: ${BOT_PASSWORD}
admins: 
  - ${ADMIN_ID}
data_dir: ${DATA_DIR}

giveme20:
  base_url: ${GIVEME20_URL}
  update_interval: ${GIVEME20_UPDATE_INTERVAL}
  groups_id:
    - ${GIVEME20_GROUP_ID}

b23live:
  update_interval: ${B23LIVE_UPDATE_INTERVAL}
